name: moauth
version: 1.0
summary: OAuth 2.0 Authorization and Resource Server
description: |
  mOAuth is a basic OAuth 2.0 client/server implementation that is geared towards
  testing and development of OAuth-based services.  The client library supports
  authorization of native macOS, iOS, and Linux applications with PKCE.

  The server is both an Authorization Server and a Resource Server that supports:

  - User account authentication/authorization using PAM
  - Traditional web-based authorization grants with redirection as well as
    resource owner password credentials grants
  - Token introspection for services
  - Basic Resource Server functionality with implicit and explicit ACLs
  - Customizable web interface

grade: stable
confinement: strict
icon: moauth.png

apps:
    moauthd:
        command: $SNAP/sbin/moauthd
        daemon: simple
        plugs: [home, network, network-bind]

parts:
    main:
        plugin: autotools
        source: .

build-packages: [libcups-dev]
