name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout mOAuth
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update Build Environment
      run: sudo apt-get update --fix-missing -y
    - name: Install Prerequisites
      run: sudo apt-get install -y cppcheck avahi-daemon libavahi-client-dev libssl-dev libpam-dev libusb-1.0-0-dev zlib1g-dev
    - name: Configure mOAuth
      run: ./configure --enable-debug --enable-maintainer --with-sanitizer --disable-shared
    - name: Build mOAuth
      run: make
    - name: Test mOAuth
      env:
        ASAN_OPTIONS: leak_check_at_exit=false
      run: cd moauth; make test
#    - name: clang static analyzer
#      run: make CC=clang "GHA_ERROR=::error::" clang
#    - name: cppcheck
#      run: make "GHA_ERROR=::error::" cppcheck

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout mOAuth
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure mOAuth
      run: ./configure --enable-debug --enable-maintainer --with-sanitizer --disable-shared
    - name: Build mOAuth
      run: make
    - name: Test mOAuth
      run: cd moauth; make test
#    - name: clang static analyzer
#      run: make CC=clang "GHA_ERROR=::error::" clang
